# exec_always --no-startup-id $HOME/Pictures/wallpapers/anime_24_catppuccin_mocha_blue.jpg play-local /home/liva/live-shit/batman-black-judgment.1920x1080.mp4
output eDP-1 bg $HOME/Pictures/wallpapers/anime_24_catppuccin_mocha_blue.jpg fill
output eDP-1 mode 1920x1080@60Hz
