output eDP-1 bg $HOME/Pictures/wallpapers/arch-black-4k.png fill
output eDP-1 mode 1920x1080@60Hz
# exec_always --no-startup-id $HOME/Pictures/wallpapers/arch-black-4k.png Rosé Pine.png play-local /home/liva/live-shit/batman-black-judgment.1920x1080.mp4
