# exec_always --no-startup-id $HOME/Pictures/wallpapers/haikyuu_final.jpg play-local /home/liva/live-shit/batman-black-judgment.1920x1080.mp4
output eDP-1 bg $HOME/Pictures/wallpapers/haikyuu_final.jpg fill
output eDP-1 mode 1920x1080@60Hz
