blur enable
blur_xray disable
blur_passes 2
blur_radius 2
# blur_contrast 1.2
# blur_noise 0.0
# blur_brightness 1.0
# corner_radius 5

# layer_effects "waybar" {
#     corner_radius 5;
# }
# shadows enable
# shadow_color #89B4FA
# shadow_blur_radius 22
# shadow_offset 0 0
