#####################################################################################################
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """
$directory\
$git_branch\
$git_status\
$c\
$java\
$kotlin\
$python\
$dart\
$docker_context
$character"""

palette = 'catppuccin'

[palettes.catppuccin]
color_fg0 = '#fafdf6'
color_bg1 = '#282A36'
color_bg3 = '#665c54'
color_blue = '#42a5f5'
color_aqua = '#689d6a'
color_green = '#50FA7B'
color_orange = '#e85d04'
color_purple = '#ff0054'
color_red = '#d62828'
color_yellow = '#ffb300'
color_black = '#080808'
purple = '#8B5CF6'

[os]
disabled = false
style = "fg:color_red"

[os.symbols]
Redhat = "󱄛"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛 "
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚 "
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "bold fg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󰉍 "
"Music" = "󰝚 "
"Pictures" = " "
"Development" = "󰲋 "

[git_branch]
symbol = "󰊢 "
style = "purple"
format = "[$symbol$branch](purple) "

[git_status]
format = "[$all_status$ahead_behind](red) "
modified = "●"
untracked = "+"
staged = "✓"
deleted = "✗"
ahead = "↑"
behind = "↓"
conflicted = "⚡"

[nodejs]
symbol = "󰎙 "
format = "[$symbol$version](green) "

[python]
symbol = "󰌠 "
format = "[$symbol$version](blue) "

[rust]
symbol = "󱘗 "
format = "[$symbol$version](red) "

[java]
symbol = "󰬷 "
format = "[$symbol$version](red) "

[golang]
symbol = "󰟓 "
format = "[$symbol$version](blue) "

[c]
symbol = "󰙱 "
format = "[$symbol$version](blue) "

[kotlin]
symbol = "󱈙 "
format = "[$symbol$version](purple) "

[dart]
symbol = "󰻈 "
format = "[$symbol$version](blue) "

[php]
symbol = "󰌟 "
format = "[$symbol$version](purple) "

[docker_context]
symbol = "󰡨 "
format = "[$symbol$context](blue) "

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[ $time](fg:white)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'

[custom.countdown]
command = "~/bin/countdown"
when = "test -x ~/bin/countdown"
format = "[$output ](fg:color_red)"

[cmd_duration]
min_time = 500
format = '[ ](fg:color_orange)$duration '

[fill]
symbol = '─'
style = 'fg:color_yellow'
