#!/usr/bin/bash

chosen=$(printf "Power\nApplications\nFiles\nTheme\nExit" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/powermenu.rasi"')

case "$chosen" in
"Power") $HOME/.config/custom_scripts/power.sh ;;
"Applications") rofi -show drun -disable-history -show-icons ;;
"Files") rofi -show filebrowser -show-icons ;;
"Clipboard") clipman pick -t rofi ;;
"Theme") $HOME/.config/custom_scripts/change_theme ;;
"Exit") echo "" ;;
*) echo "No theme selected" ;;
esac
